version: '2'
services:
  client:
    build: .
    container_name: linalgo-annotation-client
    volumes:
    - annotation-client:/srv/client/build
    - ./src:/srv/client/src
    env_file:
    - docker-compose.env
    ports:
    - "3000:3000"
    - "3001:3001"
    command:
    - gulp
    - watch
volumes:
  annotation-client:
    external: true # README: run: docker volume create annotation-client